language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: release
    if: branch = master
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: release
      script: npm run release
    - stage: deploy
      script: npm publish

