language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: test
  - name: update_version
    if: branch = master
jobs:
  include:
    - stage: update_version
      script: ./deploy/update_version.sh
