language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: update_version
    if: branch = master
jobs:
  include:
    - stage: update_version
      script: git config user.name ${USER}
    - script: git config user.email ${EMAIL}
    - script: npm run release
    - script: git push "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" origin "${TRAVIS_BRANCH}" --follow-tags
