language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: test
  - name: update_version
    if: head_branch = deploy AND type = pull_request
jobs:
  include:
    - stage: update_version
      script: ./deploy/update_version.sh
