language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: test
  - name: update_version
jobs:
  include:
    - stage: test
      script: skip
    - stage: update_version
      script: ./deploy/update_version.sh
