language: node_js
node_js:
- '8'
- '10'
stages:
- name: test
  if: type = push
- name: update_version
  if: commit_message =~ /Merge pull request.+/
jobs:
  include:
  - stage: update_version
    script: "./deploy/update_version.sh"
before_deploy: npm run build
deploy:
  provider: npm
  email: kiwi71728@icloud.com
  api_key:
    secure: C3SUUQlyO2Yd+XTNJPC0ZF3p5eFe7CO/5gb4oh4fnxqCdBJTjoH0dPxMmWiFdZ5sZA8lrWFxzxUJD7VuoIC0Ln2+YMtZnEvSqXHKSiJzMLedTBoIlu9g1GpWeTARMgqBkCD7F55efpzUsF4k9OBwmpzbrlI+05E7zA5UZ4HIdExJgTNlee9QNAT7OJHNiCYQukQ14ClB3EWAU3KsRq3sULMhC9jugpkLQeAAO38P4QC2ZuHGx4eSruJx1Zo3FS1mSGLbhZvGgY6fVNjxRw+clO5RHxlG3TGZ2NqiNTdh8o0raiiry/NK7nXArTY1g+ruTmHERLFn3b8xiBfn72ckiZdwrUGtHlEcCxhrOdLuYHkPwS3gkpHjnoy/UKyCWQNyRKpqKzy54Qeq2hK2BHxUgGo85wqXmKw2EYV4+jmEZLa7T8XCZWduK1mkXoewA5ykYfByAVPWcuQhPqKnpr/YiA8H0zW7ctiRWlKrL4ZSDGMM1E30CVGEtYrUevSLH0jNXrh5WNuqPQc+f3JNNxPcRber6rkHfkKVAxoN9AhU6aT++t22DVaefIHiUtQhOudUE9Cf7yo+BBdy/zzG3Vqk1CwTnfdmgMd33rFD6AwkIP0FtY/Isnsc01AFBWENLNrMEum3bGztfUB6Bn1P24EwBxlx4Op48WKYOgx3hWLpo4E=
  on:
    tags: true
    branch: master
    repo: dustin71728/event-sequence-listener
    node: '10'
  skip_cleanup: true
