language: node_js
node_js:
  - "8"
  - "10"
stages:
  - name: test
    if: type = push
  - name: update_version
    if: branch = master AND type = pull_request AND commit_message = /Merge pull request/
jobs:
  include:
    - stage: update_version
      script: ./deploy/update_version.sh
